### ISSUE TITLE
Token Structure and Collisions

### ISSUE THREAD

**Issue by jkinley** [lukasoppermann/style-dictionary-utils#10]
Hi Lukas! Thanks so much for making these utils. Look forward to being able to help collaborate on this if I can be of assistance. 

Not sure this is a bug, but I am posting this here, bc there is no discussion session. I am happy to discuss elsewhere if you wish, but I thought this might help others too. Here is a warning I am getting from your utilities:

<img width="770" alt="image" src="https://github.com/lukasoppermann/style-dictionary-utils/assets/19417886/0ed721de-7731-4603-8b26-e1c0192469bb">

I am trying to structure core tokens with the prefix core as in your article here: https://uxdesign.cc/naming-design-tokens-9454818ed7cb

Here are some examples of how I structure the tokens: 

<img width="555" alt="Screenshot 2023-06-14 at 11 53 12 AM" src="https://github.com/lukasoppermann/style-dictionary-utils/assets/19417886/a66bf9dd-08ef-46b0-bf5e-4cd9bb27b6cc">

<img width="786" alt="Screenshot 2023-06-14 at 11 53 07 AM" src="https://github.com/lukasoppermann/style-dictionary-utils/assets/19417886/e0f60ca3-52ae-4e70-a24a-6b922df46923">

<img width="465" alt="Screenshot 2023-06-14 at 11 53 00 AM" src="https://github.com/lukasoppermann/style-dictionary-utils/assets/19417886/89567370-69aa-4911-81c5-bee57fecf25e">

Given those collision warnings, am I doing this wrong? Any ideas on how to achieve the "core" prefix without causing the collisions?

**Comment by jkinley** [comment]
I think I am silly. I just adjusted like so and it seems the collisions are gone.! Does this approach make sense you?

<img width="539" alt="Screenshot 2023-06-14 at 11 59 41 AM" src="https://github.com/lukasoppermann/style-dictionary-utils/assets/19417886/716af6ae-cc3e-4925-9742-9f31c1d7b9c1">
<img width="453" alt="Screenshot 2023-06-14 at 11 59 51 AM" src="https://github.com/lukasoppermann/style-dictionary-utils/assets/19417886/1b8998a2-50b7-4186-9617-111a71662392">

**Comment by lukasoppermann** [comment]
Hey @jkinley, yes the setup looks good to me. Are you getting the expected output?

**Comment by jkinley** [comment]
yes! aside from my initial mistake it seems to be working well. Thanks!
