### ISSUE TITLE
Nested defaults

### ISSUE THREAD

**Issue by jkinley** [lukasoppermann/style-dictionary-utils#11]
I was wondering  'style-dictionary-utils' can support nested default values like here: https://github.com/amzn/style-dictionary/issues/716

I am trying to do something like this so that token names don't have to have "default" appended:

```
color: {
    "$type": 'color',
    background: {
      primary: {
        '@': {"$value": '{core.color.brand-blue.500}'},
        light: {"$value": '{core.color.brand-blue.200}'},
        dark: {"$value": '{core.color.brand-blue.800}'},
      },
```

This is currently breaking for me:

<img width="593" alt="image" src="https://github.com/lukasoppermann/style-dictionary-utils/assets/19417886/e256e8be-c5c4-4019-a132-4c42da61ce1b">

**Comment by lukasoppermann** [comment]
Hmm, are you sure this is breaking because of the  `@`?

Can you create a [codesandbox.io](https://codesandbox.io) or [codepen.io](https://codepen.io) so we can test with your config and file setup?

**Comment by jkinley** [comment]
Update. I was not using the "@" when referencing the token. I am not sure if this is how its suppose to work, but here is a working example for future reference:


Given this semantic font-weight token:
<img width="545" alt="Screenshot 2023-06-15 at 8 40 06 AM" src="https://github.com/lukasoppermann/style-dictionary-utils/assets/19417886/e1892a2a-fe0f-47a7-96ad-f0bfaba962f5">

This is compiling correctly:

<img width="1369" alt="Screenshot 2023-06-15 at 8 40 52 AM" src="https://github.com/lukasoppermann/style-dictionary-utils/assets/19417886/e7664a96-62de-4495-8f8a-903331bbe6f6">

**Comment by jkinley** [comment]
UPDATE

I figured it out. My problem came when referencing the token. I was not including the "@" when referencing. See here for more details: https://github.com/amzn/style-dictionary/issues/119. Also, it looks like a lot of people want a better way to do this in SD 4.0. Here is what worked for me:

<img width="545" alt="Screenshot 2023-06-15 at 8 40 06 AM" src="https://github.com/lukasoppermann/style-dictionary-utils/assets/19417886/989ab85c-98d1-471b-a43f-459d56d09f1c">

<img width="1369" alt="Screenshot 2023-06-15 at 8 40 52 AM" src="https://github.com/lukasoppermann/style-dictionary-utils/assets/19417886/1442e229-f358-4e5b-90e7-71e9296edb5d">

**Comment by jkinley** [comment]
Thanks again for the help!
