### ISSUE TITLE
Composite Tokens not working

### ISSUE THREAD

**Issue by jkinley** [lukasoppermann/style-dictionary-utils#12]
Not sure why I can't get composite tokens to work correctly. Here is a stackblitz:

https://stackblitz.com/edit/style-dictionary-example-3n61r6?file=tokens%2Fcomposite.json5

**Comment by lukasoppermann** [comment]
Hey, the problem is that you are using the css transform group instead of the custom transformers.

The css transform group is a build in group in style dictionary.

You can extend the group like so:

```diff
!| import SD from 'style-dictionary';
import StyleDictionary from 'style-dictionary-utils';
import parser from 'style-dictionary-utils/dist/parser/w3c-token-json5-parser.js';
StyleDictionary.registerParser(parser.w3cTokenJson5Parser);


// to run type: "node ./build.mjs"
const myStyleDictionary = StyleDictionary.extend({
  source: ['tokens/**/*.json5'],
  format: {
    test: ({ dictionary }) => {
      return JSON.stringify(dictionary.tokens, null, 2);
    },
  },
  platforms: {
    css: {
!|       transforms: [...SD.transformGroup['css'], 'shadow/css'],
      buildPath: 'build/css/',
      files: [
        {
          filter: () => true,
          destination: 'variables.css',
          format: 'css/variables',
        },
      ],
    },
  },
});

myStyleDictionary.buildAllPlatforms();
```

**Comment by jkinley** [comment]
ah. Thanks so much. Sorry, this tooling isn't exactly in my wheelhouse.

**Comment by lukasoppermann** [comment]
No worries, happy to help.

**Comment by jkinley** [comment]
> No worries, happy to help.

Lukas! Works like a charm. I really appreciate all your efforts to help push design tokens forward. I also have occasional chats with Danny Banks. Even had him come talk to our team a couple years ago. Anyway, I was wondering if we might be able to start a forum somewhere to have open discussions on this type of stuff. I have not discovered anything yet and have been researching tokens for a while now. Still can't find great examples of 3 tier system (core, semantic, component). Do know if there are some resources or places I have missed?

**Comment by lukasoppermann** [comment]
Hey @jkinley,

I am happy to open the discussions of this repo, but I guess that would be more focused in the actual project here and you are looking for a forum on design tokens at large, right?

I do some writing on medium and a few other design token folks do as well. This and looking at design systems and how other teams do it, feels like the best resources for me at the moment.
