### ISSUE TITLE
Accept prettier configuration for formatters

### ISSUE THREAD

**Issue by rossyman** [lukasoppermann/style-dictionary-utils#13]
Can we expose the ability to configure `prettier`, which is used in the `javascript/esm` and `javascript/commonJs` formatters? This would allow consumers of your library to define the output format of generated files in order to ensure compliance with individual project constraints.

https://github.com/lukasoppermann/style-dictionary-utils/blob/f4f8aded5a89887a54f1f994dadf70888d1111f1/src/format/javascript-esm.ts#L15

https://github.com/lukasoppermann/style-dictionary-utils/blob/f4f8aded5a89887a54f1f994dadf70888d1111f1/src/format/javascript-commonJs.ts#L22

**Comment by lukasoppermann** [comment]
Hey, are you saying you would like to pass the options to prettier?

Like 

```js
  return format(output, {parser: 'typescript', printWidth: 500, ...options.prettier}) 
```

Which would be provided to the formatter as an argument?

**Comment by rossyman** [comment]
Yeah exactly @lukasoppermann -- Sorry for the late response.
