### ISSUE TITLE
Should Transforms work at group level?

### ISSUE THREAD

**Issue by jkinley** [lukasoppermann/style-dictionary-utils#17]
According to the W3C Spec, the Type is supposed to be allowed to set at the group level. 
<img width="832" alt="image" src="https://github.com/lukasoppermann/style-dictionary-utils/assets/19417886/c89c7913-9c8b-4b4b-be98-87573674ac00">

With the current 'dimension/pixelToRem' transformer, the type has to be set on each value like this:

```
{
  core: {
    spacing: {
      sm: {"$type": 'dimension', "$value": '1px'},
      md: {"$type": 'dimension',"$value": '2px'},
      lg: {"$type": 'dimension',"$value": '4px'}
    }
  }
}
```

But shouldn't the transformer work in this case too?

```
  core: {
    spacing: {
      "$type": 'dimension',
      sm: {"$value": '1px'},
      md: {"$value": '2px'},
      lg: {"$value": '4px'}
    }
  }
}
```

**Comment by lukasoppermann** [comment]
Hey @jkinley, if I remember correctly style dictionary does not process `$types` of the parents, so you can't access the value inside the transformer. But this needs to be tested, as I am not sure.

Feel free to add a simple `console.log(token.$type)` inside the dimension transformer and change the test code like you suggest. Maybe there is also a way to check the parent, but we would have to look through the style dictionary docs or the issues there.

If this does work, I agree we should make it work for all transformers.

**Comment by jkinley** [comment]
Thanks! I will have my colleague Doug look into this. Another thing this make me think about: Do you know how well these utils will sync up with the new version of Style Dictionary that Danny plans on releasing later this year? I think he's going to make it plugin based, so some of this stuff we are utilizing should cross-over nicely, right?

**Comment by lukasoppermann** [comment]
I will update this package once the new version is released.
