### ISSUE TITLE
Build dist + publish to npm

### ISSUE THREAD

**Issue by wolfflow** [lukasoppermann/style-dictionary-utils#2]
Hey! Happy to use `style-dictionary` and `design-tokens` so far, yet I'd suggest to include built dist in npm module and have some typings as well

**Comment by lukasoppermann** [comment]
Happy to accept PRs. This is on my to-do list though, but if you want to help it is always welcome.

**Comment by lukasoppermann** [comment]
Fixed in [v1.1.0](https://github.com/lukasoppermann/style-dictionary-utils/releases/tag/v1.1.0)
