### ISSUE TITLE
Do we need a transform for a composite clamp() output?

### ISSUE THREAD

**Issue by jkinley** [lukasoppermann/style-dictionary-utils#23]
Wondering what your take on this is, Lukas. I am thinking something like this:

Input

```
{
  'responsive-heading': {
    '$value': {
      'min': '1.5rem',
      'ideal': '5vw',
      'max': '2.5rem'
    }
  }
}
```

Output 

```
--responsive-heading: clamp(1.5rem, 5vw, 2.5rem);

```

**Comment by lukasoppermann** [comment]
Hmm, I am wondering if we could solve this with an array. This would also need a custom type.

```js
{
  'responsive-heading': {
    '$type': 'clamp', // or minMax?
    '$value': [1.5,5,2.5]
  }
}
```

If we consider adding this we should maybe also consider a minMax with only a min and a max value?

This is all very css specific, right?

**Comment by jkinley** [comment]
It is very CSS specific. I think type should be clamp to be inline with 'cubicBezier'. That way the type is equal to the CSS function. The tricky part is the array. It needs to support different units. But that shouldn't matter, right? If this makes sense, I can get Doug to work on it and add it to your repo.

**Comment by lukasoppermann** [comment]
I guess maybe, if we have different values and since clamp needs those three arguments, the composite token idea you suggested is best in the end:

```js
{
  'responsive-heading': {
    '$type': 'clamp',
    '$value': {
       'min': '1.5rem',
       'ideal': '5vw',
       'max': '2.5rem'
    }
  }
}
```

This of course means at least within the clamp type we need to support more dimension types: `px`, `rem`, `vw`, `vh`, `%`.

**Comment by jkinley** [comment]
@lukasoppermann Thanks for the feedback, Lukas. I have my colleague Doug taking a look at this. While we are on this topic, I just wanted to mention that ideally, the second argument ( preferred size ) would ideally accept an expression.

```css

h4 {
  font-size: clamp(minValue, preferredValue, maxValue);
}

```

Ideally, we'd want the 2nd argument to handle an expression like `0.5vw + 0.75rem`. So the CSS would look like this:

```css

h4 {
  font-size: clamp(16px, 0.5vw + 0.75rem, 19px);
}

``` 
Please note that `calc` is not required inside `clamp()` as it can handle expressions on its own. For more information, see this article here: https://www.aleksandrhovhannisyan.com/blog/fluid-type-scale-with-css-clamp/
