### ISSUE TITLE
Expand composite tokens

### ISSUE THREAD

**Issue by mikepaggi-abbvie** [lukasoppermann/style-dictionary-utils#36]
@lukasoppermann it would be great if we could expand out composite tokens such as border and typography to be individual tokens.

Instead of just border for example, we would get compiled out border-width, border-style....etc

**Comment by lukasoppermann** [comment]
Hey, this is a great idea. 

As far as I know style dictionary does not allow us to split tokens like this though.

I guess what would be possible is to create multiple input tokens and add transformers for those.

E.g.

```js
{
  border: {
    style: {
      dotted: {
        $type: "string",
        $value: "dotted"
      }
    }
  }
}
```

What do you think about this? Or do you have a different option?

**Comment by mikepaggi-abbvie** [comment]
Yeah, that's the issue my team has run into is that style dictionary can't split out tokens or allow creating new tokens overall as part of the build process.

We actually did something very similar to what you mentioned to achieve what we wanted, so we had to move away from composites on Border and Typography but keeping Shadow.

``` json
"border": {
  "style": {
     "solid": {
       "$value": "solid",
        "$type": "strokeStyle"
     }
  }
}

**Comment by lukasoppermann** [comment]
Okay, so I am going to close this for now as it can't be done until style dict adds this feature.
