### ISSUE TITLE
dimension-to-pixelUnitless returns a string for 0

### ISSUE THREAD

**Issue by lauriejones** [lukasoppermann/style-dictionary-utils#39]
Hey again 👋 

I noticed that on [this line](https://github.com/lukasoppermann/style-dictionary-utils/blob/main/src/transformer/dimension-to-pixelUnitless.ts#L47) in the `dimension-to-pixelUnitless` transform, `0` is returned as a string `'0'` when all other values are returned as a number.

![image](https://github.com/lukasoppermann/style-dictionary-utils/assets/11398624/c4eff09f-873f-40f5-81b3-ec3722fb8f45)

This is causing some issues for us when we try to set appropriate `resolvedTypes/scopes` in figma. Is there any reason why this behaves this way?

**Comment by lukasoppermann** [comment]
Great point. Do you want to send a PR? Otherwise I can fix it.

**Comment by lauriejones** [comment]
Happy to create a PR. Should this if statement just be removed or changed to return `0`/`floatVal`?

**Comment by lukasoppermann** [comment]
we need to change the return value to the `number` `0`. Otherwise if you use `0` instead of `0px` for values it would not be returned at all.
