### ISSUE TITLE
w3cTokenJsonParser and ':' character

### ISSUE THREAD

**Issue by dj-kmuldoon** [lukasoppermann/style-dictionary-utils#4]
Some JSON editing apps introduce a space before and after the colon. Suggest updating w3cTokenJsonParser so does not include the colon (or can parse with or without space).

**BEFORE:**
`const preparedContent = (contents || '{}').replace(/"\$?value":/g, '"value":')`

**AFTER:**
`const preparedContent = (contents || '{}').replace(/"\$?value"/g, '"value"')`

**Comment by lukasoppermann** [comment]
Fixed in [v1.1.1](https://github.com/lukasoppermann/style-dictionary-utils/releases/tag/v1.1.1)
