### ISSUE TITLE
color2k is missing in dependencies

### ISSUE THREAD

**Issue by varya** [lukasoppermann/style-dictionary-utils#41]
It seems that the util cannot find `color2k` package. The issue was solved when I added `color2k` as a dependency to my own project.
![2023-11-28_13-59-44](https://github.com/lukasoppermann/style-dictionary-utils/assets/27215/4ed0254e-8cc9-4bfc-9511-6ec2bdc2079c)

**Comment by lukasoppermann** [comment]
This is because it was a `peerDependency` however, to make it easier to use I now moved all peerDeps to deps.
