### ISSUE TITLE
2.0.2 to 2.0.5 requires new modules locally

### ISSUE THREAD

**Issue by mikepaggi-abbvie** [lukasoppermann/style-dictionary-utils#42]
Noticed I had to install color2k now. is this a requirement on our side to maintain?

**Comment by lukasoppermann** [comment]
Wait, the change was actually to move it to `devDependencies` (was a `peerDependencies`) before. It should be installed automatically via `npm i`

**Comment by mikepaggi-abbvie** [comment]
@lukasoppermann when I did npm upgrade (not sure if thats the best way anymore or just do npm i), it didn't seem to build correctly until I added that in since I do use some of the color conversion.

**Comment by lukasoppermann** [comment]
Yes, this makes sense. Idk how to prevent this, but upgrade would probably not install newly added deps I guess. Any idea how this can be solved? Not the biggest npm expert. 😄

**Comment by mikepaggi-abbvie** [comment]
@lukasoppermann that's a good question, as I personally thought npm upgrade would trigger those new dependencies to be downloaded automatically. maybe in case others complain, just mention in docs or something to use npm i and not upgrade 😄. we can probably close this issue if you want otherwise

**Comment by mikepaggi-abbvie** [comment]
@lukasoppermann actually this might be a bug on your side? I noticed that if I remove color2k and do "npm i" then it isn't installing that module. I'm getting errors that it is not there until I add it into my devDependencies to be downloaded

**Comment by lukasoppermann** [comment]
Hey, I may have understood the issue. Can you pull the latest version and try again?

**Comment by mikepaggi-abbvie** [comment]
Perfect :-) , thanks for the quick turn around
