### ISSUE TITLE
Registering custom transforms

### ISSUE THREAD

**Issue by cailborg** [lukasoppermann/style-dictionary-utils#5]
Since i'm calling this instead of the original style dictionary, does this library allow me to register custom transforms? I'm following the style dictionary docs and any custom transforms don't seem to be applying.

**Comment by lukasoppermann** [comment]
Yes, this should work fine, I added a new section to the readme and some tests: https://github.com/lukasoppermann/style-dictionary-utils#extending-style-dictionary

If it does not work, please provide some more details, so I can help debug it.

**Comment by cailborg** [comment]
I think I have narrowed down my issue. I can get the transform to output fine when there is no matcher on the `registerTransform`

When I add a matcher for `prop.attributes.category === 'color'` suddenly nothing matches. I know I have a matching color value because when i use `"filter": "isColor"` in my config, I get the expected match.

If you have an example of a custom transform with a working matcher, i'd love to see it.

Working code:
```
StyleDictionary.registerTransform({
    name: 'hexToFigma',
    type: 'value',
    transformer: (token) => {
        if (token.value.startsWith('#')) {
            return hexToFigma(token.value)
        }
        return token.value;
    }
});
```

With an input of `#E0ECFA` I get the expected output of
```
{
            "r": 224,
            "g": 236,
            "b": 250
          }
```

**Comment by cailborg** [comment]
I think I have solved my issue, I had to register a custom `attribute/cti` transform to be able to match a category

```
StyleDictionary.registerTransform({
    name: 'attribute/cti', 
    type: 'attribute',
      transformer: function(token) {
        type MyObject = {
            [key: string]: any;
          };
        const attrNames = ['category', 'type', 'item', 'subitem', 'state'];
        const originalAttrs = token.attributes || {};
        const generatedAttrs: MyObject =  {}
  
        for(let i=0; i<token.path.length && i<attrNames.length; i++) {
          let attr = token.path[i];
          console.log(attr);
          if (attr === "colors") { attr = "color" };
          generatedAttrs[attrNames[i]] = attr;
        }
  
        return Object.assign(generatedAttrs, originalAttrs);
      }
  });
```

Not sure why, but happy to close this issue
