### ISSUE TITLE
All rem conversion are 16 basePxFontSize

### ISSUE THREAD

**Issue by jdgaravito** [lukasoppermann/style-dictionary-utils#52]
Hi, I have a bug, no matter which basPxFontSize i choose I always get a 16px base conversion:

here is my code:
´´´
import StyleDictionary from 'style-dictionary-utils';

StyleDictionary.registerTransformGroup({
	name: 'CssRem',
	transforms: [
		'attribute/cti',
		'dimension/pixelToRem',
		'name/cti/kebab',
		'time/seconds',
		'color/css',
		'gradient/css',
		'cubicBezier/css',
		'content/icon'
	]
});

const config = {

	source: ["src/styles/tokens/*.json"],
	platforms: {
		css: {
			buildPath: "src/styles/build/css/",
			transformGroup: "CssRem",
			files: [
				{
					destination: "dt_tokens.css",
					format: "css/variables",
					options: {
						outputReferences: true,
						// this is the value for 62.5% converted to decimal in order to have 10px base system.
						basePxFontSize: 0.625
					}
				}
			]
		}
	}

}

const sd = StyleDictionary.extend(config);
sd.buildAllPlatforms();

´´´
I tested 16px, 18px and always 1rem = 16px.

what I'm doing wrong?

**Comment by lukasoppermann** [comment]
Hey,

so there are two issues I think: 
1. You should set it to a px value so `10` and not `0.625`
2. `basePxFontSize` is an option on the `Platform config` not an the `file config`


So, it needs to be nested like `css.basePxFontSize`:

```js
source: ["src/styles/tokens/*.json"],
platforms: {
	css: {
	  basePxFontSize: 10
```
Here is the test for it: https://github.com/lukasoppermann/style-dictionary-utils/blob/main/__tests__/transformer/dimension-pixel-to-rem.test.ts#L29
