### ISSUE TITLE
Implementing TypeScript/ESM-Declarations

### ISSUE THREAD

**Issue by douglaszaltron** [lukasoppermann/style-dictionary-utils#55]
A standardized format called 'typescript/esm-declarations' is proposed to facilitate the generation of TypeScript types in design (UI) libraries. This approach aims to simplify the integration and usage of these libraries in projects using TypeScript, enhancing interoperability and development experience.

 What are your thoughts on this proposal?

draft:

```
function jsonToTypes(
  json,
  indent = "  ",
  rootName = "DesignToken",
  isRoot = true
) {
  let result = isRoot ? `export type ${rootName} = {\n` : "{\n";

  Object.entries(json).forEach(([key, value]) => {
    result += `${indent}'${key}': `;
    if (typeof value === "object" && value !== null) {
      result += jsonToTypes(value, `${indent}  `, rootName, false);
    } else {
      result += `${typeof value};\n`;
    }
  });

  result += `${indent.slice(0, -2)}};\n`;
  return result;
}
```

```
files: [
        {
          destination: "variables.ts",
          format: "javascript/esm",
        },
        {
          destination: "variables.d.ts",
          format: "typescript/esm-declarations",
        },
      ],
      ```

**Comment by lukasoppermann** [comment]
When you say:
> A standardized format called 'typescript/esm-declarations' is proposed to facilitate the generation of TypeScript types in design (UI) libraries. 

Are you talking about this issue, or is there somewhere proposal to be added to all libs?

As for your proposal, looks nice. We would need a PR with an implementation and tests to verify it works. However, if it works fine, I am very happy to merge it. 👍
