### ISSUE TITLE
Camel casing the ESM output

### ISSUE THREAD

**Issue by Wildhoney** [lukasoppermann/style-dictionary-utils#74]
I've seen [this issue](https://github.com/amzn/style-dictionary/issues/257) with `nested/json` which claims to have been resolved, but I still seem to have the same issue.

Essentially using:

```ts
ts: {
  transforms: ["name/cti/camel"],
  buildPath: "build/",
  files: [
    {
      filter: "isSource",
      destination: "tokens.ts",
      format: "javascript/esm",
    },
  ],
}
```

I would expect the output map to be camel cased, but it isn't. Is this not possible?

Instead I get:

```ts
export default {
  "border-radius": {
    small: "5px",
    medium: "10px",
    large: "20px",
  }
}
```

**Comment by lukasoppermann** [comment]
Hey, 
`name/cti/camel` or any `cti` transformer does not work in most cases.
However, I just added a new transformer to solve the problem for you [name/pathtocamelcase](https://github.com/lukasoppermann/style-dictionary-utils?tab=readme-ov-file#namepathtocamelcase)

**Comment by Wildhoney** [comment]
Thank you 🙏
