### ISSUE TITLE
Style dictionary 4.0 support?

### ISSUE THREAD

**Issue by mikepaggi-abbvie** [lukasoppermann/style-dictionary-utils#78]
I thought I saw somewhere about 4.0 style dictionary support? If not is there a plan to migrate to it?

Thanks :-)

**Comment by lukasoppermann** [comment]
Sadly I have to rework the PR. I was on vacation but am back so this should be merged soon. Sorry for the delay cc: @haraldvinje

**Comment by lukasoppermann** [comment]
Released: https://github.com/lukasoppermann/style-dictionary-utils/releases/tag/v3.0.0
