### ISSUE TITLE
SyntaxError: 'default' export not found in 'style-dictionary-utils' module

### ISSUE THREAD

**Issue by ron-thomas-george** [lukasoppermann/style-dictionary-utils#84]
When attempting to import style-dictionary-utils in my project, I encountered the following error: 
SyntaxError: The requested module 'style-dictionary-utils' does not provide an export named 'default'.

**Comment by lukasoppermann** [comment]
Hey @ron-thomas-george,

this is true and a bug in the docs which I will fix.

You need to use a named import:

```js
import {StyleDictionary} from 'style-dictionary-utils';
```

**Comment by ron-thomas-george** [comment]
Okay.

**Comment by lukasoppermann** [comment]
Updated the docs, should be alright now.

**Comment by MathisPct** [comment]
Same sort as problem here

```
TS2307: Cannot find module style-dictionary-utils or its corresponding type declarations.

There are types at
C:/DESIGN TOKEN/design-token-JSON-to-x-style-dictionnary/node_modules/style-dictionary-utils/dist/index. d. ts
, but this result could not be resolved under your current moduleResolution setting. Consider updating to node16, nodenext, or bundler
```

Please find below my `tsconfig`

```json
{
  "compilerOptions": {
    "module": "CommonJS",
    "esModuleInterop": true,
    "rootDir": "./src",
    "outDir": "dist",
    "target": "es6",
    "strict": true,
    "resolveJsonModule": true,
    "typeRoots": ["./types", "./node_modules/@types", "./node_modules/"],
  },
  "include": [
    "src/**/*"
  ]
}
```

**Comment by lukasoppermann** [comment]
@ron-thomas-george sorry another update I missed, it is all async now:

```js
import { StyleDictionary } from "style-dictionary-utils";
const myStyleDictionary = new StyleDictionary();

const extendedSD = await myStyleDictionary.extend({
  source: ["tokens/**/*.tokens.json"],
  platforms: {
    css: {
      buildPath: "dist/css/",
      transformGroup: "css",
      files: [
        {
          format: "css/variables",
          destination: "variables.css",
        },
      ],
    },
  },
});

extendedSD.buildAllPlatforms();
```

**Comment by ron-thomas-george** [comment]
@lukasoppermann Yeah. It's working now.

**Comment by ron-thomas-george** [comment]
@MathisPct No. I haven't pushed my code to Github. Will share the repo once it's done.

**Comment by MathisPct** [comment]
> Same sort of problem here
> 
> ```
> [Typescript] src/token-builder.ts(1,33): error TS2307: Cannot find module 'style-dictionary-utils' or its corresponding type declarations.
> [Typescript]   There are types at 'C:/DESIGN TOKEN/design-token-JSON-to-x/node_modules/style-dictionary-utils/dist/index.d.ts', but this result could not be resolved under your current 'moduleResolution' setting. Consider updating to 'node16', 'nodenext', or 'bundler'.
> [Typescript] 
> [Typescript] 14:23:40 - Found 1 error. Watching for file changes.
> ```
> 
> Please find below my `tsconfig`
> 
> ```json
> {
>   "compilerOptions": {
>     "module": "CommonJS",
>     "esModuleInterop": true,
>     "rootDir": "./src",
>     "outDir": "dist",
>     "target": "es6",
>     "strict": true,
>     "resolveJsonModule": true,
>     "typeRoots": ["./types", "./node_modules/@types", "./node_modules/"],
>   },
>   "include": [
>     "src/**/*"
>   ]
> }
> ```
> 
> And my code
> 
> ```ts
> import { StyleDictionary } from 'style-dictionary-utils';
> 
> const myStyleDictionary = new StyleDictionary()
> 
> interface BuildConfig {
>     outputDirectory: string
> }
> 
> export async function buildCssVariables(buildConfig: BuildConfig, theme: string) {
>     await myStyleDictionary.extend({
>         platforms: {
>             css: {
>                 buildPath: `${buildConfig.outputDirectory}/${theme}/`,
>                 transformGroup: 'css/extended',
>                 destination: "tokens.css",
>                 files: [{
>                     format: "css/advanced",
>                     options: {
>                         selector: `body[theme="dark"]`, // defaults to :root; set to false to disable
>                     }
>                 }]
>             }
>         }
>     });
>     await myStyleDictionary.buildAllPlatforms();
> }
> ```
> 
> I think it's because of my config but I don't know how to manage it to resolve the Node Error

I resolved my problem thanks to this beautifull answer :D

https://stackoverflow.com/a/72380008/13343559

**Comment by lukasoppermann** [comment]
Yeah @MathisPct since style dictionary moved to `esm` we all need to move. Great that you found the solution.

I updated the docs to add the `await` now.
